### ISSUE TITLE
麻烦不要在头文件里面定义print宏

### ISSUE THREAD

**Issue by tsingakbar** [yanyiwu/limonp#17]
很容易跟别的库冲突的
这种宏真的除了污染global名字空间什么用都没有
https://github.com/yanyiwu/limonp/blob/03d46d2a768498170dcc76611b952134b9ffccb6/include/limonp/StdExtension.hpp#L32

**Comment by yanyiwu** [comment]
确实容易冲突，提个pr去掉？
